export * from "../src/missing.mjs";

/* Manually adapted ../vendor/compiler/_namespaces/ts.js file */
export * from "../vendor/compiler/corePublic";
export * from "../vendor/compiler/core";
export * from "../vendor/compiler/debug";
export * from "../vendor/compiler/semver";
// export * from "../vendor/compiler/performanceCore";
// export * from "../vendor/compiler/perfLogger";
// export * from "../vendor/compiler/tracing";
export * from "../vendor/compiler/types";
export * from "../vendor/compiler/sys";
export * from "../vendor/compiler/path";
export * from "../vendor/compiler/diagnosticInformationMap.generated";
export * from "../vendor/compiler/scanner";
export * from "../vendor/compiler/utilitiesPublic";
export * from "../vendor/compiler/utilities";
export * from "../vendor/compiler/factory/baseNodeFactory";
export * from "../vendor/compiler/factory/parenthesizerRules";
export * from "../vendor/compiler/factory/nodeConverters";
export * from "../vendor/compiler/factory/nodeFactory";
export * from "../vendor/compiler/factory/emitNode";
export * from "../vendor/compiler/factory/emitHelpers";
export * from "../vendor/compiler/factory/nodeTests";
export * from "../vendor/compiler/factory/utilities";
export * from "../vendor/compiler/factory/utilitiesPublic";
export * from "../vendor/compiler/parser";
export * from "../vendor/compiler/commandLineParser";
export * from "../vendor/compiler/moduleNameResolver";
export * from "../vendor/compiler/binder";
export * from "../vendor/compiler/symbolWalker";
export * from "../vendor/compiler/checker";
export * from "../vendor/compiler/visitorPublic";
export * from "../vendor/compiler/sourcemap";
export * from "../vendor/compiler/transformers/utilities";
export * from "../vendor/compiler/transformers/namedEvaluation";
// export * from "../vendor/compiler/transformers/destructuring";
// export * from "../vendor/compiler/transformers/taggedTemplate";
// export * from "../vendor/compiler/transformers/ts";
// export * from "../vendor/compiler/transformers/classFields";
// export * from "../vendor/compiler/transformers/typeSerializer";
// export * from "../vendor/compiler/transformers/legacyDecorators";
// export * from "../vendor/compiler/transformers/esDecorators";
// export * from "../vendor/compiler/transformers/es2017";
// export * from "../vendor/compiler/transformers/es2018";
// export * from "../vendor/compiler/transformers/es2019";
// export * from "../vendor/compiler/transformers/es2020";
// export * from "../vendor/compiler/transformers/es2021";
// export * from "../vendor/compiler/transformers/esnext";
// export * from "../vendor/compiler/transformers/jsx";
// export * from "../vendor/compiler/transformers/es2016";
// export * from "../vendor/compiler/transformers/es2015";
// export * from "../vendor/compiler/transformers/es5";
// export * from "../vendor/compiler/transformers/generators";
// export * from "../vendor/compiler/transformers/module/module";
// export * from "../vendor/compiler/transformers/module/system";
// export * from "../vendor/compiler/transformers/module/esnextAnd2015";
// export * from "../vendor/compiler/transformers/module/node";
export * from "../vendor/compiler/transformers/declarations/diagnostics";
export * from "../vendor/compiler/transformers/declarations";
export * from "../vendor/compiler/transformer";
export * from "../vendor/compiler/emitter";
export * from "../vendor/compiler/watchUtilities";
export * from "../vendor/compiler/program";
// export * from "../vendor/compiler/builderStatePublic";
// export * from "../vendor/compiler/builderState";
export * from "../vendor/compiler/builder";
// export * from "../vendor/compiler/builderPublic";
export * from "../vendor/compiler/resolutionCache";
export * from "../vendor/compiler/watch";
// export * from "../vendor/compiler/watchPublic";
export * from "../vendor/compiler/tsbuild";
// export * from "../vendor/compiler/tsbuildPublic";
